# Generated by Django 4.1.7 on 2023-07-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP PROCEDURE IF EXISTS sp_get_posts;

            CREATE PROCEDURE sp_get_posts(IN _text VARCHAR(250), IN date_from DATE,
                        IN date_to DATE,
                        IN perpage INT,
                        IN npage INT,
                        IN order_by VARCHAR(255),
                        IN orden VARCHAR(4), IN business_id INT)
            BEGIN
                
                DECLARE cc INT;

                SET npage=perpage*(npage-1);
            
                select count(*) into cc
                from posts_posts pp 
                where pp.deleted_at is null
                and if(business_id is null, true, pp.business_id = business_id)
                AND IF(date_from IS NULL OR date_to IS NULL, TRUE, (DATE(pp.created_at) >= date_from AND DATE(pp.created_at) <= date_to));
                
                select pp.content, pp.created_at, pp.published_at, pp.image_url, pp.status
                from posts_posts pp 
                where pp.deleted_at is null
                and if(business_id is null, true, pp.business_id = business_id)
                AND IF(date_from IS NULL OR date_to IS NULL, TRUE, (DATE(pp.created_at) >= date_from AND DATE(pp.created_at) <= date_to))
                ORDER BY pp.created_at desc LIMIT perpage OFFSET npage;

            END
        """)]
