# Generated by Django 4.1.7 on 2023-08-31 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_ocassion', models.CharField(max_length=255)),
                ('post_promo', models.CharField(max_length=255)),
                ('post_objective', models.CharField(max_length=255)),
                ('post_language', models.CharField(choices=[('Spanish', 'Spanish'), ('English', 'English')], max_length=10)),
                ('post_use_emojis', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('post_keywords', models.JSONField()),
                ('post_creativity', models.FloatField()),
                ('post_copy_size', models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('post_include_business_info', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('role', models.CharField(max_length=50)),
                ('chosen', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
    ]
