# Generated by Django 4.1.7 on 2023-09-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230904_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='products_to_include',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
