# Generated by Django 4.1.7 on 2023-09-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postdetail_products_to_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='selectable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
