# Generated by Django 4.1.7 on 2023-09-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_messages_selectable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
    ]
