# Generated by Django 4.1.7 on 2023-09-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_sp_get_posts_20232908_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='products_to_include_names',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
