# Generated by Django 4.1.7 on 2023-09-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postdetail_products_to_include_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSurvey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostSurveyAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('post_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postsurvey')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.surveyquestion')),
            ],
        ),
    ]
