# Generated by Django 4.1.7 on 2023-09-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_postsurvey_surveyquestion_postsurveyanswer'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO posts_surveyquestion(name, created_at) VALUES('¿Qué tan persuasivo es el copy para captar la atención del público objetivo y generar interés en el producto o servicio?', '2023-09-11 22:54:57');"
        ),
        migrations.RunSQL(
            "INSERT INTO posts_surveyquestion(name, created_at) VALUES('¿Qué tan claro y conciso es el mensaje del copy? ¿Comunica de manera efectiva los beneficios y propuesta de valor del producto o servicio?', '2023-09-11 22:54:57');"
        ),
        migrations.RunSQL(
            "INSERT INTO posts_surveyquestion (name, created_at) VALUES('¿Cómo de relevante es el copy para el público objetivo y su contexto? ¿Se adapta a sus necesidades, deseos y preocupaciones?', '2023-09-11 22:54:57');"
        ),

        migrations.RunSQL(
            "INSERT INTO posts_surveyquestion (name, created_at) VALUES('¿Qué tan creativo y original es el copy? ¿Logra destacarse y diferenciarse de la competencia?', '2023-09-11 22:54:57');"
        ),
        
        migrations.RunSQL(
            "INSERT INTO posts_surveyquestion (name, created_at) VALUES('¿Qué tan efectivamente utiliza el copy elementos persuasivos como ganchos emocionales, pruebas sociales o llamados a la acción?', '2023-09-11 22:54:57');"
        ),
    ]